### ISSUE TITLE
Unable to create GISO

### ISSUE THREAD

**Issue by matheripper** [ios-xr/gisobuild#17]
Hi
I try to create the GISO on a Ubuntu 22.04.
System requirements check passed, but creation fails.
Any help is appreciated
thanks in advance for your help

root@tzhpemac-ubu20:/home/tzhpemac/GISO# sudo ./gisobuild/src/gisobuild.py --iso /home/tzhpemac/GISO/RPM/ASR9K-x64-iosxr-7.4.2/asr9k-mini-x64-7.4.2.iso --repo /home/tzhpemac/GISO/RPM/7.4.2_SMU/ --clean
System requirements check [PASS]
Traceback (most recent call last):
  File "/home/tzhpemac/GISO/./gisobuild/src/gisobuild.py", line 513, in <module>
    main()
  File "/home/tzhpemac/GISO/./gisobuild/src/gisobuild.py", line 509, in main
    execute_build(cli_args)
  File "/home/tzhpemac/GISO/gisobuild/src/exrmod/isotools_exr.py", line 40, in execute_build
    system_build_main (cli_args, infile)
  File "/home/tzhpemac/GISO/gisobuild/src/exrmod/gisobuild_exr.py", line 101, in main
    giso.set_giso_info(argv.bundle_iso)
  File "/home/tzhpemac/GISO/gisobuild/src/exrmod/gisobuild_exr_engine.py", line 2056, in set_giso_info
    if not args.optimize:
AttributeError: 'Namespace' object has no attribute 'optimize'

root@tzhpemac-ubu20:/home/tzhpemac/GISO# sudo ./gisobuild/src/gisobuild.py --version
gisobuild.py (version 1.0)

root@tzhpemac-ubu20:/home/tzhpemac/GISO# more /home/tzhpemac/GISO/gisobuild/src/output_gisobuild/logs/gisobuild.log-2022-06-21:11:03:19.032310
2022-06-21 11:03:19::  Performing System requirements check...
2022-06-21 11:03:19::  Available space 30.58446502685547 GB
2022-06-21 11:03:19::  Required space 14.372596740722656 GB
2022-06-21 11:03:19::  System requirements check [PASS]
2022-06-21 11:03:42::  Cleaning Iso

**Comment by vkoulermos** [comment]
same here

```
# ./gisobuild/src/gisobuild.py --iso isos/asr9k-mini-x64-7.5.2.iso --repo repo/goldenRPMs/ --label gisov1 --migration
System requirements check [PASS]
Traceback (most recent call last):
  File "./gisobuild/src/gisobuild.py", line 513, in <module>
    main()
  File "./gisobuild/src/gisobuild.py", line 509, in main
    execute_build(cli_args)
  File "/root/giso/gisobuild/src/exrmod/isotools_exr.py", line 40, in execute_build
    system_build_main (cli_args, infile)
  File "/root/giso/gisobuild/src/exrmod/gisobuild_exr.py", line 101, in main
    giso.set_giso_info(argv.bundle_iso)
  File "/root/giso/gisobuild/src/exrmod/gisobuild_exr_engine.py", line 2056, in set_giso_info
    if not args.optimize:
AttributeError: 'Namespace' object has no attribute 'optimize'
```

**Comment by cmohapat** [comment]
Issue has been fixed in latest gisobuild tool. Request to try in latest tool to build GISO.

**Comment by matheripper** [comment]
thank you,  process to create the giso was successful
