### ISSUE TITLE
GISO build with tar files including sysadmin in repo doesn't work

### ISSUE THREAD

**Issue by skwsk** [ios-xr/gisobuild#22]
When put tar files under repo, if the it has sysadmin SMU tar file, the GISO build for eXR failed. I think validate_and_return_list() in gisobuild_exr_engine.py require similar logic for "if pkg.endswith('.tar'):" as "elif pkg.endswith('.rpm'):" to treat sysadmin SMUs.

The below is error message. I've put some debug lines so the line numbers in below error are not aligned with original source code.
```
Traceback (most recent call last):
  File "/opt/giso/./gisobuild/src/gisobuild.py", line 532, in <module>
    main()
  File "/opt/giso/./gisobuild/src/gisobuild.py", line 528, in main
    execute_build(cli_args)
  File "/opt/giso/gisobuild/src/exrmod/isotools_exr.py", line 40, in execute_build
    system_build_main (cli_args, infile)
  File "/opt/giso/gisobuild/src/exrmod/gisobuild_exr.py", line 193, in main
    rpm_db.populate_rpmdb(fs_root, argv.rpmRepo, pkglist,
  File "/opt/giso/gisobuild/src/exrmod/gisobuild_exr_engine.py", line 703, in populate_rpmdb
    self.tmp_smu_repo_path, repo_files = Rpmdb.validate_and_return_list(platform, repo_paths, pkglist)
  File "/opt/giso/gisobuild/src/exrmod/gisobuild_exr_engine.py", line 551, in validate_and_return_list
    result = run_cmd(cmd)
  File "/opt/giso/gisobuild/src/exrmod/gisobuild_exr_engine.py", line 114, in run_cmd
    raise RuntimeError("Error CMD=%s returned --->%s" % (cmd, out))
RuntimeError: Error CMD=rpm -qpR /opt/giso/output/R08_ISO_01/tmppo67pzdn/ncs5500-sysadmin-hostos-7.2.1.1-r721.CSCvv89835.host.arm.rpm | grep -e ncs5500 | grep  ' = ' returned --->warning: /opt/giso/output/R08_ISO_01/tmppo67pzdn/ncs5500-sysadmin-hostos-7.2.1.1-r721.CSCvv89835.host.arm.rpm: Header V4 RSA/SHA256 Signature, key ID 5746bd08: NOKEY
```

**Comment by cmohapat** [comment]
Ack. we will fix and update.
