### ISSUE TITLE
iosls.py index error

### ISSUE THREAD

**Issue by tylersiemers** [ios-xr/gisobuild#30]
Running the following helper script for LNT isols.py
located at src/lntmod

The command referenced in this guide fails on python3.6

https://xrdocs.io/8000/tutorials/8000-software-xr7-giso/#giso-verification

root@NA----DEV-Machine:~/gisobuild/src/lntmod# ./isols.py /root/gisobuild/nsight_builds/builds/N540L_752_v4/giso/ncs540l-golden-x86_64-7.5.2-N540L_752_v4.iso --optional-packages
Traceback (most recent call last):
  File "./isols.py", line 28, in <module>
    sys.path.append(str(pathlib.Path(__file__).parents[1]))
  File "/usr/lib/python3.6/pathlib.py", line 594, in __getitem__
    raise IndexError(idx)
IndexError: 1

Changing the script to the following works

`#!/usr/bin/env python3
# ----------------------------------------------------------------

""" Wrapper script to extract ISO information.

Copyright (c) 2022 Cisco and/or its affiliates.
This software is licensed to you under the terms of the Cisco Sample
Code License, Version 1.1 (the "License"). You may obtain a copy of the
License at

        https://developer.cisco.com/docs/licenses

All use of the material herein must be in accordance with the terms of
the License. All rights not expressly granted by the License are
reserved. Unless required by applicable law or agreed to separately in
writing, software distributed under the License is distributed on an "AS
IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
or implied.

"""

__all__ = ()

from pathlib import Path
import sys

sys.path.append(str(Path(__file__).resolve().parents[1]))
from lnt import tools

if __name__ == "__main__":
    tools.isols(sys.argv[1:])`

**Comment by NeilKetley** [comment]
Hi Ty,

Thanks for raising this issue.  I have created an internal ticket for the issue.  We will create a fix using your suggestion and push it through our tests and release process.

Cheers
Neil
