### ISSUE TITLE
gisobuild not working

### ISSUE THREAD

**Issue by hmntsharma** [ios-xr/gisobuild#41]
```
╭─lab at netdevops in ~/github/gisobuild/src on master✔ 24-03-27 - 15:45:52
╰─(vntdvops) ⠠⠵ ./gisobuild.py --iso ~/cisco7_11_1/asr9k-mini-x64-7.11.1.iso --repo ~/cisco7_11_1/*.rpm --pkglist ~/cisco7_11_1/asr9k-isis-x64-1.0.0.0-r7111.x86_64.rpm
Traceback (most recent call last):
  File "/home/lab/github/gisobuild/src/utils/gisoutils.py", line 181, in is_platform_exr
    files_top = _subprocs.execute(
                ^^^^^^^^^^^^^^^^^^
  File "/home/lab/github/gisobuild/src/utils/_subprocs.py", line 106, in execute
    return _execute_internal(
           ^^^^^^^^^^^^^^^^^^
  File "/home/lab/github/gisobuild/src/utils/_subprocs.py", line 70, in _execute_internal
    proc = subprocess.run(
           ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.11/subprocess.py", line 1950, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'isoinfo'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/lab/github/gisobuild/src/./gisobuild.py", line 531, in <module>
    main()
  File "/home/lab/github/gisobuild/src/./gisobuild.py", line 448, in main
    cli_args = validate_and_setup_args(cli_args)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lab/github/gisobuild/src/./gisobuild.py", line 320, in validate_and_setup_args
    args.exriso = gisoutils.is_platform_exr (args.iso)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lab/github/gisobuild/src/utils/gisoutils.py", line 191, in is_platform_exr
    raise AssertionError(
AssertionError: Failed to determine input ISO image type.
╭─lab at netdevops in ~/github/gisobuild/src on master✔ 24-03-27 - 15:46:28
╰─(vntdvops) ⠠⠵ ll ~/cisco7_11_1
total 1.7G
-rw-r--r-- 1 lab lab 3.7M Mar 27 15:04 asr9k-isis-x64-1.0.0.0-r7111.x86_64.rpm
-rw-r--r-- 1 lab lab 1.6M Mar 27 15:04 asr9k-k9sec-x64-1.0.0.0-r7111.x86_64.rpm
-rw-r--r-- 1 lab lab  13M Mar 27 15:04 asr9k-mcast-x64-1.0.0.0-r7111.x86_64.rpm
-rw-r--r-- 1 lab lab  21M Mar 27 15:04 asr9k-mgbl-x64-1.0.0.0-r7111.x86_64.rpm
-rw-r--r-- 1 lab lab 1.7G Mar 27 15:04 asr9k-mini-x64-7.11.1.iso
-rw-r--r-- 1 lab lab 8.6M Mar 27 15:04 asr9k-mpls-te-rsvp-x64-1.0.0.0-r7111.x86_64.rpm
-rw-r--r-- 1 lab lab 2.2M Mar 27 15:04 asr9k-mpls-x64-1.0.0.0-r7111.x86_64.rpm
-rw-r--r-- 1 lab lab 4.0M Mar 27 15:04 asr9k-ospf-x64-1.0.0.0-r7111.x86_64.rpm
╭─lab at netdevops in ~/github/gisobuild/src on master✔ 24-03-27 - 15:46:33
╰─(vntdvops) ⠠⠵
```

**Comment by hmntsharma** [comment]
It's been a while. I forgot to run the prep_dependency.sh in setup dir. It works after that. Sorry!
