### ISSUE TITLE
FileNotFound Error or File already exists

### ISSUE THREAD

**Issue by asdat3** [ios-xr/gisobuild#43]
either it kills itself cause there is already such a directory or it kills itself when there isnt the "GisoMountDir" whatever that is... (when u run without --clean)

```
cc@matze-vm-001:~/golden_iso_generation/gisobuild$ ./src/gisobuild.py --iso ncs540-mini-x-6.6.3.iso --out-directory test --clean
Traceback (most recent call last):
  File "/home/cc/golden_iso_generation/gisobuild/./src/gisobuild.py", line 531, in <module>
    main()
  File "/home/cc/golden_iso_generation/gisobuild/./src/gisobuild.py", line 527, in main
    execute_build(cli_args)
  File "/home/cc/golden_iso_generation/gisobuild/src/exrmod/isotools_exr.py", line 38, in execute_build
    system_resource_check (cli_args)
  File "/home/cc/golden_iso_generation/gisobuild/src/exrmod/gisobuild_exr.py", line 71, in system_resource_check
    disk = os.statvfs(args.out_directory)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'test'

cc@matze-vm-001:~/golden_iso_generation/gisobuild$ 
cc@matze-vm-001:~/golden_iso_generation/gisobuild$ ./src/gisobuild.py --iso ncs540-mini-x-6.6.3.iso --out-directory ./test --clean
Traceback (most recent call last):
  File "/home/cc/golden_iso_generation/gisobuild/./src/gisobuild.py", line 531, in <module>
    main()
  File "/home/cc/golden_iso_generation/gisobuild/./src/gisobuild.py", line 527, in main
    execute_build(cli_args)
  File "/home/cc/golden_iso_generation/gisobuild/src/exrmod/isotools_exr.py", line 38, in execute_build
    system_resource_check (cli_args)
  File "/home/cc/golden_iso_generation/gisobuild/src/exrmod/gisobuild_exr.py", line 71, in system_resource_check
    disk = os.statvfs(args.out_directory)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: './test'
cc@matze-vm-001:~/golden_iso_generation/gisobuild$ ./src/gisobuild.py --iso ncs540-mini-x-6.6.3.iso --label test
Error: Tool chroot not found.
Failed to find pre-req tools, Check PATH Env variable or install required tools.
Error: System requirements check [FAIL]
cc@matze-vm-001:~/golden_iso_generation/gisobuild$ sudo ./src/gisobuild.py --iso ncs540-mini-x-6.6.3.iso --label test
Output directory /home/cc/golden_iso_generation/gisobuild/output_gisobuild exists. 
Consider passing --clean as input or remove directory and rerun.
[Errno 17] File exists: '/home/cc/golden_iso_generation/gisobuild/output_gisobuild'
cc@matze-vm-001:~/golden_iso_generation/gisobuild$ sudo ./src/gisobuild.py --iso ncs540-mini-x-6.6.3.iso --label test --clean
System requirements check [PASS]
Traceback (most recent call last):
  File "/home/cc/golden_iso_generation/gisobuild/./src/gisobuild.py", line 531, in <module>
    main()
  File "/home/cc/golden_iso_generation/gisobuild/./src/gisobuild.py", line 527, in main
    execute_build(cli_args)
  File "/home/cc/golden_iso_generation/gisobuild/src/exrmod/isotools_exr.py", line 40, in execute_build
    system_build_main (cli_args, infile)
  File "/home/cc/golden_iso_generation/gisobuild/src/exrmod/gisobuild_exr.py", line 168, in main
    giso.set_giso_info(argv.bundle_iso)
  File "/home/cc/golden_iso_generation/gisobuild/src/exrmod/gisobuild_exr_engine.py", line 2263, in set_giso_info
    self.do_extend_giso(self.bundle_iso.iso_mount_path)
  File "/home/cc/golden_iso_generation/gisobuild/src/exrmod/gisobuild_exr_engine.py", line 2331, in do_extend_giso
    with open(GisoMountDir+"/giso_info.txt", 'r') as fd:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/cc/golden_iso_generation/gisobuild/output_gisobuild/tmpbnuruukb/giso_info.txt'
```

**Comment by asdat3** [comment]
`
Fatal error: GISO build 'docker run --name giso-93643d085e87d6df162e8cf3 -v /home/cc/golden_iso_generation/gisobuild/src:/app/gisobuild:ro -v /home/cc/golden_iso_generation/gisobuild/src/ncs540files/NCS540-iosxr-k9-6.6.3.tar:/home/cc/golden_iso_generation/gisobuild/src/ncs540files/NCS540-iosxr-k9-6.6.3.tar:ro -v /home/cc/golden_iso_generation/gisobuild/src/test/lz759s7y:/home/cc/golden_iso_generation/gisobuild/src/test/lz759s7y:ro -v /home/cc/golden_iso_generation/gisobuild/src/ncs540files:/home/cc/golden_iso_generation/gisobuild/src/ncs540files:ro ciscogisobuild/cisco-xr-gisobuild:2.3.4 /app/gisobuild/gisobuild.py --yamlfile /home/cc/golden_iso_generation/gisobuild/src/test/lz759s7y/cliConfig.yaml' failed with exit code 1
Traceback (most recent call last):
  File "/app/gisobuild/gisobuild.py", line 531, in <module>
    main()
  File "/app/gisobuild/gisobuild.py", line 527, in main
    execute_build(cli_args)
  File "/app/gisobuild/exrmod/isotools_exr.py", line 40, in execute_build
    system_build_main (cli_args, infile)
  File "/app/gisobuild/exrmod/gisobuild_exr.py", line 168, in main
    giso.set_giso_info(argv.bundle_iso)
  File "/app/gisobuild/exrmod/gisobuild_exr_engine.py", line 2263, in set_giso_info
    self.do_extend_giso(self.bundle_iso.iso_mount_path)
  File "/app/gisobuild/exrmod/gisobuild_exr_engine.py", line 2331, in do_extend_giso
    with open(GisoMountDir+"/giso_info.txt", 'r') as fd:
FileNotFoundError: [Errno 2] No such file or directory: '/home/cc/golden_iso_generation/gisobuild/src/test/tmpk97jdykt/tmphsinli7k/giso_info.txt'
Error: GISO build 'docker run --name giso-93643d085e87d6df162e8cf3 -v /home/cc/golden_iso_generation/gisobuild/src:/app/gisobuild:ro -v /home/cc/golden_iso_generation/gisobuild/src/ncs540files/NCS540-iosxr-k9-6.6.3.tar:/home/cc/golden_iso_generation/gisobuild/src/ncs540files/NCS540-iosxr-k9-6.6.3.tar:ro -v /home/cc/golden_iso_generation/gisobuild/src/test/lz759s7y:/home/cc/golden_iso_generation/gisobuild/src/test/lz759s7y:ro -v /home/cc/golden_iso_generation/gisobuild/src/ncs540files:/home/cc/golden_iso_generation/gisobuild/src/ncs540files:ro ciscogisobuild/cisco-xr-gisobuild:2.3.4 /app/gisobuild/gisobuild.py --yamlfile /home/cc/golden_iso_generation/gisobuild/src/test/lz759s7y/cliConfig.yaml' failed with exit code 1
Error: Traceback (most recent call last):
Error:   File "/app/gisobuild/gisobuild.py", line 531, in <module>
Error:     main()
Error:   File "/app/gisobuild/gisobuild.py", line 527, in main
Error:     execute_build(cli_args)
Error:   File "/app/gisobuild/exrmod/isotools_exr.py", line 40, in execute_build
Error:     system_build_main (cli_args, infile)
Error:   File "/app/gisobuild/exrmod/gisobuild_exr.py", line 168, in main
Error:     giso.set_giso_info(argv.bundle_iso)
Error:   File "/app/gisobuild/exrmod/gisobuild_exr_engine.py", line 2263, in set_giso_info
Error:     self.do_extend_giso(self.bundle_iso.iso_mount_path)
Error:   File "/app/gisobuild/exrmod/gisobuild_exr_engine.py", line 2331, in do_extend_giso
Error:     with open(GisoMountDir+"/giso_info.txt", 'r') as fd:
Error: FileNotFoundError: [Errno 2] No such file or directory: '/home/cc/golden_iso_generation/gisobuild/src/test/tmpk97jdykt/tmphsinli7k/giso_info.txt'
`

idk what I am supposed to do wrong

**Comment by pvpanda** [comment]
Could you please Walk me through how you are building the GISO ?

Regards,
Tejeswar

**Comment by asdat3** [comment]
all good, got it working
