### ISSUE TITLE
Error "isoinfo"

### ISSUE THREAD

**Issue by ajakuma8** [ios-xr/gisobuild#48]
Hi Team, I am getting below error while creating GISO. Please help me resolve this issue.

ajay@DESKTOP-FN59VNI:/mnt/c/Ubuntu$ sudo python3 gisobuild.py --iso ncs5500-mini-x-7.9.2.iso --repo TEST -l v1
Traceback (most recent call last):
  File "/mnt/c/Ubuntu/utils/gisoutils.py", line 181, in is_platform_exr
    files_top = _subprocs.execute(
  File "/mnt/c/Ubuntu/utils/_subprocs.py", line 106, in execute
    return _execute_internal(
  File "/mnt/c/Ubuntu/utils/_subprocs.py", line 70, in _execute_internal
    proc = subprocess.run(
  File "/usr/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'isoinfo'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/c/Ubuntu/gisobuild.py", line 531, in <module>
    main()
  File "/mnt/c/Ubuntu/gisobuild.py", line 448, in main
    cli_args = validate_and_setup_args(cli_args)
  File "/mnt/c/Ubuntu/gisobuild.py", line 320, in validate_and_setup_args
    args.exriso = gisoutils.is_platform_exr (args.iso)
  File "/mnt/c/Ubuntu/utils/gisoutils.py", line 191, in is_platform_exr
    raise AssertionError(
AssertionError: Failed to determine input ISO image type.

**Comment by dpacific84** [comment]
Please try to use the gisobuild on a Debian based linux distribution
Ubuntu based distribution has known limitations
