### ISSUE TITLE
says no yaml, but it installed

### ISSUE THREAD

**Issue by ilyapetrashkevich** [ios-xr/gisobuild#49]
trying to build GISO image. created venv and installed pyyaml to to that virtual environment, but it still complains on lack of yaml library..
As you may see yaml library is there.

Please help...
Thank you in advance!

I'm using latest debian version on wsl.

```
user@IPHP:~$ python3.11 -m venv .venv
user@IPHP:~$ source .venv/bin/activate
(.venv) user@IPHP:~$ pip3 install pyyaml
Collecting pyyaml
  Downloading PyYAML-6.0.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (762 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 763.0/763.0 kB 9.4 MB/s eta 0:00:00
Installing collected packages: pyyaml
Successfully installed pyyaml-6.0.2
(.venv) user@IPHP:~$ cd gisobuild/src/
(.venv) user@IPHP:~/gisobuild/src$ sudo python3.11 gisobuild.py --iso repo/asr9k-mini-x64-7.11.21.iso --repo repo/* --clean
Traceback (most recent call last):
  File "/home/user/gisobuild/src/gisobuild.py", line 625, in <module>
    main()
  File "/home/user/gisobuild/src/gisobuild.py", line 621, in main
    execute_build(cli_args)
  File "/home/user/gisobuild/src/exrmod/isotools_exr.py", line 27, in execute_build
    from exrmod import gisobuild_exr
  File "/home/user/gisobuild/src/exrmod/gisobuild_exr.py", line 21, in <module>
    from exrmod.gisobuild_exr_engine import *
  File "/home/user/gisobuild/src/exrmod/gisobuild_exr_engine.py", line 34, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'
(.venv) user@IPHP:~/gisobuild/src$
(.venv) user@IPHP:~/gisobuild/src$ python3.11
Python 3.11.2 (main, Aug 26 2024, 07:20:54) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import yaml
>>> exit()
```

**Comment by ilyapetrashkevich** [comment]
forgot to mention it here - it was not working in ubuntu 24.04, but in 22.04 I saw no such strange issues
