### ISSUE TITLE
qemu: uncaught target signal 11 (Segmentation fault)  in GISO creation. 

### ISSUE THREAD

**Issue by OrnelasE** [ios-xr/gisobuild#51]
Hello! 

I tried to create the next GISO containing: 
+ ncs5500-mini-x-7.5.2.iso
-rw-r--r-- 1  501 dialout 114M Nov 11 17:28 ncs5500-7.5.2.CSCwk94350.tar
-rw-r--r-- 1 8413 floppy  661K Apr 26  2022 ncs5500-eigrp-1.0.0.0-r752.x86_64.rpm
-rw-r--r-- 1 8413 floppy  3.5M Apr 26  2022 ncs5500-isis-2.1.0.0-r752.x86_64.rpm
-rw-r--r-- 1 8413 floppy  346K Apr 26  2022 ncs5500-li-1.0.0.0-r752.x86_64.rpm
-rw-r--r-- 1 8413 floppy  9.5K Apr 26  2022 ncs5500-lictrl-1.0.0.0-r752.x86_64.rpm
-rw-r--r-- 1 8413 floppy   13M Apr 26  2022 ncs5500-mcast-3.0.0.0-r752.x86_64.rpm
-rw-r--r-- 1 8413 floppy   21M Apr 26  2022 ncs5500-mgbl-3.0.0.0-r752.x86_64.rpm
-rw-r--r-- 1 8413 floppy  2.4M Apr 26  2022 ncs5500-mpls-2.1.0.0-r752.x86_64.rpm
-rw-r--r-- 1 8413 floppy  4.0M Apr 26  2022 ncs5500-ospf-2.0.0.0-r752.x86_64.rpm

But each time I have: 
```
root@11:/gisobuild/src# ./gisobuild.py --iso /ncs5500-mini-x-7.5.2.iso --repo /RPM/
/gisobuild/src/exrmod/gisobuild_exr_engine.py:102: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if contEnvPath.exists() and contEnvPath.read_text().find("cubes") is not -1:
System requirements check [PASS]

Platform: ncs5500 Version: 7.5.2

Scanning repository [/RPM]...

Building RPM Database...
Traceback (most recent call last):
  File "/gisobuild/src/./gisobuild.py", line 625, in <module>
    main()
  File "/gisobuild/src/./gisobuild.py", line 621, in main
    execute_build(cli_args)
  File "/gisobuild/src/exrmod/isotools_exr.py", line 40, in execute_build
    system_build_main (cli_args, infile)
  File "/gisobuild/src/exrmod/gisobuild_exr.py", line 267, in main
    rpm_db.populate_rpmdb(fs_root, argv.rpmRepo, pkglist,
  File "/gisobuild/src/exrmod/gisobuild_exr_engine.py", line 795, in populate_rpmdb
    rpm.populate_mdata(fs_root, os.path.basename(file_name), 
  File "/gisobuild/src/exrmod/gisobuild_exr_engine.py", line 359, in populate_mdata
    group_info = run_cmd(gen_cmd)
  File "/gisobuild/src/exrmod/gisobuild_exr_engine.py", line 129, in run_cmd
    raise RuntimeError("Error CMD=%s returned --->%s" % (cmd, out))
RuntimeError: Error CMD=chroot /gisobuild/src/output_gisobuild/tmpx909lkm5 rpm -qp --qf '%{GROUP}' ncs5500-mpls-te-rsvp-3.1.0.0-r752.x86_64.rpm returned --->qemu: uncaught target signal 11 (Segmentation fault) - core dumped
```

**Comment by OrnelasE** [comment]
By the way, I am using Debiant 11.2 in a docker container. I followed https://xrdocs.io/8000/tutorials/8000-software-xr7-giso/ to set it up.

**Comment by OrnelasE** [comment]
Hello, quick update on this regard, changing the platform to amd64, helped. 
`docker run --platform=linux/amd64 --name alma_linux_8 -h 8-alma -it almalinux:8 /bin/bash -l`

And would overall recommend to use Almalinux 8 to run both, there, for both, eXR, LNT 8k platform generated the iso with no further issues.
